# This is a basic workflow to help you get started with Actions

name: POI_CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths: [ apis/poi/**, .github/workflows/PoiApi-Action.yml ]
  pull_request:
    branches: [ master ]
    paths: [ apis/poi/**, .github/workflows/PoiApi-Action.yml ]

defaults:
  run:
    working-directory: apis/poi
    
env:
  build_name: "POI_Build"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1
    - name: Install dependencies
      run: dotnet restore poi.sln
    - name: Build
      run: dotnet build poi.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test poi.sln --no-restore --verbosity normal

    - name: Create Issue on Error
      if: ${{ failure() }}
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title:  "${{ env.build_name }} Build Failed: ${{ github.workflow }}",
            body: "Build Run Failed: ${{ github.run_number }} click here for logs https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          })
