# This is a basic workflow to help you get started with Actions

name: New User Profile API CD

env:
  ACRNAME: openhackvs44eql7acr.azurecr.io
  ACRREPO: devopsoh/api-userprofile
  APPNAME: openhackvs44eql7userprofile
  HEALTHCHECK_STAGING: https://openhackvs44eql7userprofile-staging.azurewebsites.net/api/healthcheck/user
  
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths: [ apis/userprofile/**, .github/workflows/userprofile-CD.yml ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
defaults: 
  run:  
    working-directory: apis/userprofile

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  validate-staging:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Validate Staging
        run: |
          echo "Checking endpoint"
          while [ true ]; do
             result=`curl -s -o /dev/null -w "%{http_code}" $HEALTHCHECK_STAGING`
             if [ -z $result ]; then
                echo "Status from healthcheck endpoint is empty!"
                exit 1
             fi
             echo "Status from healthcheck endpoint : $result"
             if [ $result == "200" ]; then
                echo "Web service in staging seems to be running OK!"
                break
             else
                echo "Web service is not ready, sleeping 5 seconds ..."
                sleep 5
             fi
          done
