# This is a basic workflow to help you get started with Actions

name: New User Profile API CD

env:
  ACRNAME: openhackvs44eql7acr.azurecr.io
  ACRREPO: devopsoh/api-userprofile
  APPNAME: openhackvs44eql7userprofile
  HEALTHCHECK_STAGING: https://openhackvs44eql7userprofile-staging.azurewebsites.net/api/healthcheck/user
  
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths: [ apis/userprofile/**, .github/workflows/userprofile-CD.yml ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
defaults: 
  run:  
    working-directory: apis/userprofile

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  validate-staging:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run Health Check (Staging)
        run: |
          echo "Checking endpoint"
          result=`curl --write-out "%{http_code}" --silent --output /dev/null $HEALTHCHECK_STAGING`
          sleep 5
          result=`curl --write-out "%{http_code}" --silent --output /dev/null $HEALTHCHECK_STAGING`
          echo $result
          for i in {1..5}
          do
              echo "Trying $i"
              if [ $result -eq 200 ] 
              then
                  echo "Yay"
                  exit 0
              else
                  sleep 10
              fi
          done
          exit 1
        id: health-check
        