# This is a basic workflow to help you get started with Actions

name: User Profile API CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths: [ apis/userprofile/**, .github/workflows/UserAPI-action.yml ] 
  pull_request:
    branches: [ master ]
    paths: [ apis/userprofile/**, .github/workflows/UserAPI-action.yml ] 

defaults:
  run:
    working-directory: apis/userprofile

env:
  build_name: "User Profile API CI"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: Create Issue on Error
      if: ${{ failure() }}
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title:  "${{ env.build_name }} Failed: ${{ github.run_id }}",
            body: "Build Run Failed: ${{ github.run_number }} click here for logs https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          })
          
