# This is a basic workflow to help you get started with Actions

name: User Profile API CD

env:
  ACRNAME: openhackvs44eql7acr.azurecr.io
  ACRREPO: devopsoh/api-userprofile
  APPNAME: openhackvs44eql7userprofile
  
  
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths: [ apis/userprofile/**, .github/workflows/UserAPI-CD.yml ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
defaults: 
  run:  
    working-directory: apis/userprofile

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        login-server: ${{ env.ACRNAME }}
      
    - name: Build the Docker image
      run: docker build --tag ${{ env.ACRNAME }}/${{ env.ACRREPO }}:${{ github.run_id }} .
      
    - name: Docker push
      run: docker push ${{ env.ACRNAME }}/${{ env.ACRREPO }}:${{ github.run_id }}

  deploy-to-staging:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:   
    - name: Azure Login
      uses: Azure/login@v1
      creds: ${{ secrets.AZ_CREDS }}
      
    - name: Deploy to Azure Web App [Staging]
      uses: azure/webapps-deploy@v2
        app-name: ${{ env.APPNAME }}
        slot-name: staging # optional, default is production
        images: ${{ env.ACRNAME }}/${{ env.ACRREPO }}:${{ github.run_id }}
